### ISSUE TITLE
Question: passing arguments to async(promise) call

### ISSUE THREAD

**Issue by levouh** [kevinhwang91/promise-async#3]
### Feature description

Not 100% sure if discussions are used here, so making an issue instead.

---

Completely unaware of how anything in Javascript work in any way, but in the example below:

```lua
local _get_branch = function()
  return promise.new(function(resolve, reject)
    require("plenary.job")
      :new({
        command = "git",
        args = { "branch", "--show-current" },
        on_exit = function(job, rc)
          if rc == 0 then
            resolve(table.concat(job:result()))
          else
            reject()
          end
        end,
      })
      :start()
  end)
end

local _merge_base = function(branch)
  return promise.new(function(resolve, reject)
    require("plenary.job")
      :new({
        command = "git",
        args = { "merge-base", branch },
        on_exit = function(job, rc)
          if rc == 0 then
            resolve(table.concat(job:result()))
          else
            reject()
          end
        end,
      })
      :start()
  end)
end

async(function()
  local branch = await(async(_get_branch))
  print(branch)
  
  -- Want to pass `branch` to `_merge_base`here. 
  local merge_base = await(async(_merge_base, branch))
  print(merge_base)
end)
```

how can I pass `branch` to `_merge_base`?

---

Looked at `nvim-ufo` (awesome work there by the way) as well as some of the examples here, but I do not see any examples of this, which makes me assume it is not possible/intended (and I am doing something wrong).

### Describe the solution you'd like

:)

**Comment by levouh** [comment]
Looks like `await(async(pcall(func, arg1, arg2)))` works (tracing what `apcall` does in `async.lua`) but is that the best way to handle passing arguments?

**Comment by levouh** [comment]
An example from `ufo` seems to be closures:

``lua
local function tryUpdateFold(bufnr)
    return async(function()
        local winid = utils.getWinByBuf(bufnr)
        if not utils.isWinValid(winid) then
            return
        end
        -- some plugins may change foldmethod to diff
        await(utils.wait(50))
        local fb = manager:get(bufnr)
        if not fb or not utils.isWinValid(winid) or utils.isDiffOrMarkerFold(winid) then
            return
        end
        -- TODO
        -- buffer go back normal mode from diff mode will disable `foldenable` if the foldmethod was
        -- `manual` before entering diff mode. Unfortunately, foldmethod will always be `manual` if
        -- enable ufo, `foldenable` will be disabled.
        -- version will be `0` if never update folds for the buffer
        if fb.version > 0 then
            vim.wo[winid].foldenable = true
        end
        await(Fold.update(bufnr))
    end)
end
```

which makes sense, but seems like it makes things quite complicated (several nested functions in some cases)

**Comment by levouh** [comment]
Per the example above, I believe I've "figured it out", however I imagine there is an easier way:

```lua
gitlib._merge_base = function(branch, target, cwd)
  cwd = cwd or User.f.get_cwd()

  return async(function()
    return promise.new(function(resolve, reject)
      require("plenary.job")
        :new({
          command = "git",
          args = { "merge-base", branch, target },
          cwd = cwd,
          on_exit = function(job, rc)
            if rc == 0 then
              resolve(table.concat(job:result()))
            else
              reject()
            end
          end,
        })
        :start()
    end)
  end)
end
```

**Comment by kevinhwang91** [comment]
The goal of promise-async is to port [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) & [Async](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) from JavaScript to Lua.

Summary diff:
| JavaScript                                          | Lua                                             |
| --------------------------------------------------- | ----------------------------------------------- |
| `async`: as keyword at the start of a function      | `Async`/`Async.sync`: as a surrounding function |
| `await`: as keyword                                 | `await`/`Async.wait` as a function              |

In JS, `async` as keyword means that pack return result with a `Promise`, like `Promise.resolve`. In Lua, there isn't sugar for that. Must write:
```lua
return async(function()
    -- inside executor
    return {'foo'}
end)
```
to replace `async` in JS, like run `return Proimise.resolve({'foo'})`

The source code in promise-async:
https://github.com/kevinhwang91/promise-async/blob/70b09063cdf029079b25c7925e4494e7416ee995/lua/async.lua#L58
