### ISSUE TITLE
neovim ufo broken

### ISSUE THREAD

**Issue by jinzhongjia** [kevinhwang91/promise-async#7]
### Version (lua -v) or (nvim -v | head -n1)

LuaJIT 2.1.1707061634

### Operating system/version

windows/archlinux(wsl)

### How to reproduce the issue

正常进行了插件更新

neovim为 `nightly`

但这个 commit 似乎破坏了什么，[17ab3826b25067045bd2cdf65cd0029a26440d3f](https://github.com/kevinhwang91/promise-async/commit/17ab3826b25067045bd2cdf65cd0029a26440d3f)，在此之前的commit 均一切正常

导致启动 neovim 时，会导致 ufo 报告以下错误：

```
Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:
.../nvim-data/lazy/nvim-ufo/lua/ufo/provider/treesitter.lua:132: UfoFallbackException
stack traceback:
           [C]:-1: in function 'error'
           .../nvim-data/lazy/nvim-ufo/lua/ufo/provider/treesitter.lua:132: in function 'mainFunc'
           .../Local/nvim-data/lazy/nvim-ufo/lua/ufo/provider/init.lua:36: in function <Anonymous:35>
```

### Expected behavior

正常工作

### Actual behavior

error

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-ufo/commit/77e13c67f6597330d68ff82c5818934746d79086
Fixed now.
