### ISSUE TITLE
E5113: Error while calling lua chunk: /home/izelnakri/Github/promise-async/lua/async.lua:88: attempt to yield across C-call boundary

### ISSUE THREAD

**Issue by izelnakri** [kevinhwang91/promise-async#9]
### Version (lua -v) or (nvim -v | head -n1)

NVIM v0.10.0 | LuaJIT 2.1.1713773202

### Operating system/version

Linux x1-carbon 6.9.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 21 Jun 2024 19:49:19 +0000 x86_64 GNU/Linux

### How to reproduce the issue

```lua
local Promise = require("promise")
local Async = require("async")

local promise = Promise:new(function(reject, resolve)
  resolve("some result")
end)

local result = Async.wait(promise)
  vim.print("RESULT IS:")
  vim.print(result)
```

### Expected behavior

First of all, thank you for building this library! It seems well written in terms of test coverage, attention to API design etc. However when I use the promise API today in neovim I get this error:

```E5113: Error while calling lua chunk: /home/izelnakri/Github/promise-async/lua/async.lua:88: attempt to yield across C-call boundary```

Maybe it requires me to wrap stuff in weird ways etc. However this apparently can be prevented:

When I write a dummy Promise module that uses lua coroutines inside I do *not* get this error:

```lua
local Promise = {
  new = function(executor)
    local co = coroutine.create(function()
      executor(function(a)
        coroutine.yield({ "success", a })
      end, function(a)
        coroutine.yield({ "error", a })
      end)
    end)

    return co
  end,
  await = function(co)
    local success, result = coroutine.resume(co)

    return result[2]
  end,
}

local promise = Promise.new(function(resolve, reject)
  resolve("some example")
end)

local result = Promise.await(promise)
```

Why do I get this error in neovim currently? Seems like we can prevent this by making some adjustments.

### Actual behavior

This triggers: E5113: Error while calling lua chunk: /home/izelnakri/Github/promise-async/lua/async.lua:88: attempt to yield across C-call boundary

Plenary async library triggers similar error, however using coroutine or coroutine.yield is not the actual problem it seems, this might be a problem with some compatibility adjustments.

**Comment by kevinhwang91** [comment]
I think you are not a js/ts developer. Please glance [async_function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) and then check out demo.js and demo.lua.

```lua
async(function ()
    
end)
```
is equal to `async` keyword of js.

**Comment by izelnakri** [comment]
This is great, I agree. I still think after 14/15 years Im not typical js/ts developer.

JS doesnt need async method to handle promises, async keyword in front of functions is a syntactic sugar that means

‘’’js
function foo(arguments) {
     return new Promise((resolve, reject) => {
       try {
            // functionBody
           return resolve($functionReturn)
       } catch (err) {
           return reject(err)
        }
     })
}
}’’’

Ability to handle feedback is a better sign of seniority than porting some implementation and test suite to lua.

One can/should use and resolve promises without needing async keyword. I have a flight now so couldnt check the issue cause in depth, in fact I need to onboard now. Hope you’ll reconsider this issue with a more positive tone.

**Comment by kevinhwang91** [comment]
`async` keyword in demo.js for a promise is not necessary.  It's just that sign asynchronous functions with `async` for daily development.

`await` shouldn't invoke outside `async` function.

**Comment by izelnakri** [comment]
@kevinhwang91 what is your reasoning for not implementing top-level await?

**Comment by kevinhwang91** [comment]
```log
await(1)
^

ReferenceError: await is not defined
    at Object.<anonymous> (/home/kevin/WorkSpaces/test/js/test_async.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1504:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32)
    at Module._load (node:internal/modules/cjs/loader:1098:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:5)
    at node:internal/main/run_main_module:30:49

Node.js v22.5.1
```

**Comment by izelnakri** [comment]
@kevinhwang91 are you sure? Because I get this instead:

```bash
02:07:28 izelnakri ~ volta install node@22.5.1
success: installed and set node@22.5.1 (with npm@10.8.2) as default
02:07:50 izelnakri ~ node
Welcome to Node.js v22.5.1.
Type ".help" for more information.
> await(1)
1
>
```

Previous versions of node.js also provides a flag to enable top-level-await
